---
title: "Wages and Cost"
author: "ruby"
date: "2024-11-04"
output: pdf_document
---

```{r}
library(data.table)
library(ggplot2)
library(patchwork)
```

```{r}
ppermile <- fread("finalppm.csv")
Wages <- fread("Wages.csv")
HoursWorked <- fread("~/Documents/Documents - Ruby's MacBook Air/RAC Work/MotoringIndex/table32020revised/HoursWorkedbyRegion.csv")
HourlyPay <- fread("~/Documents/Documents - Ruby's MacBook Air/RAC Work/MotoringIndex/table32020revised/HourlyPaybyRegion.csv")
AnnualPay <- fread("~/Documents/Documents - Ruby's MacBook Air/RAC Work/MotoringIndex/table32020revised/AnnualPaybyRegion.csv")
WeeklyPay <- fread("~/Documents/Documents - Ruby's MacBook Air/RAC Work/MotoringIndex/table32020revised/WeeklyPaybyRegion.csv")
EarningsandHours <- fread("EarningsandHours.csv")
```

```{r}
ggplot() + geom_line(EarningsandHours, mapping = aes(x= Date, y=`Weekly earnings`, colour = "red")) + geom_line(EarningsandHours,  mapping = aes(x = Date, y = `Average weekly hours of work:All workers`))+ theme_classic()
```


```{r}
HoursWorked[, c("10 percentile", "20 percentile", "25 percentile", "30 percentile", "40 percentile", "50 percentile", "60 percentile", "70 percentile", "80 percentile", "90 percentile"):=NULL]
AnnualPay[, c("10 percentile", "20 percentile", "25 percentile", "30 percentile", "40 percentile", "50 percentile", "60 percentile", "70 percentile", "80 percentile", "90 percentile"):=NULL]
WeeklyPay[, c("10 percentile", "20 percentile", "25 percentile", "30 percentile", "40 percentile", "50 percentile", "60 percentile", "70 percentile", "80 percentile", "90 percentile"):=NULL]
HourlyPay[, c("10 percentile", "20 percentile", "25 percentile", "30 percentile", "40 percentile", "50 percentile", "60 percentile", "70 percentile", "80 percentile", "90 percentile"):=NULL]
ppermile[, c("dayofquery", "Car", "MY", "Category", "UniqueID", "DirectDebitComparison", "DirectDebitComparisonNight"):=NULL]
ppermile <- ppermile[, yearmonth := lubridate::round_date(date, "months")]
EarningsandHours <- EarningsandHours[95:390]
EarningsandHours[, c("percent changes: single month", "percent changes: 3 month average", "EndDate") :=NULL]
```

```{r}
ggplot(HourlyPay, aes(x= Date, y= Median, colour = Description)) + geom_line() + theme_classic()+ ylab("Median hourly pay (£)")
ggplot(HourlyPay, aes(x= Date, y= Mean, colour = Description)) + geom_line() + theme_classic() + ylab("Mean hourly pay (£)")

ggplot(AnnualPay, aes(x= Date, y= Median, colour = Description)) + geom_line() + theme_classic()+ ylab("Median annual pay (£)")
ggplot(AnnualPay, aes(x= Date, y= Mean, colour = Description)) + geom_line() + theme_classic() + ylab("Mean annual pay (£)")

ggplot(WeeklyPay, aes(x= Date, y= Median, colour = Description)) + geom_line() + theme_classic()+ ylab("Median weekly pay (£)")
ggplot(WeeklyPay, aes(x= Date, y= Mean, colour = Description)) + geom_line() + theme_classic() + ylab("Mean weekly pay (£)")
```


```{r}
CostofDriving <- merge(ppermile, EarningsandHours, by.x = "yearmonth", by.y="Date", all = TRUE)
CostofDriving <- CostofDriving[yearmonth >= "2020-12-30"]

CostofDriving <- CostofDriving[, WagesinPence := `Weekly earnings` * 100]
CostofDriving <- CostofDriving[, costwage := (WagesinPence / ppm)/ `Average weekly hours of work:All workers` ]
```

ppm : how much you spend for one mile
average earnings per week in pence

```{r}
ggplot(ppermile, aes(x= date, y = ppm, colour = fuel)) + geom_line() + theme_classic()+ ylim(0, NA) + theme(legend.position = "bottom") + ylab("Pence per mile")

ggplot(CostofDriving, aes(x = date, y= costwage, colour = fuel)) + geom_line() + theme_classic()+ ylim(0, NA)+ theme(legend.position = "bottom") + ylab("Hours worked to drive x miles")
```
ppm 
ppm/ weekly wage 


Petrol: Usually averages around 36 MPG
Diesel: Usually averages around 43 MPG
Hybrid: Averages around 59 MPG
Full-electric: Averages around 159 MPGe

